---
- name: Create logs directory /srv/jenkins/logs if it does not exist
  ansible.builtin.file:
    path: "/srv/jwa/logs"
    state: directory
    mode: "0755"
    owner: "root"
  tags: jenkins

- name: Copy .env file if not in jenkins workspace
  ansible.builtin.copy:
    src: /Users/jackdescombes/projects/oura_proj/.env
    dest: "/srv/jenkins/.env"
    mode: "0755"
  tags: jenkins

# - name: Copy setup.sh file if not in /srv/jenkins
#   ansible.builtin.copy:
#     src: /Users/jackdescombes/projects/oura_proj/setup.sh
#     dest: /srv/jenkins/setup.sh
#     mode: "0755"
#   tags: jenkins

- name: copy requirements file if not in /srv/jenkins
  ansible.builtin.copy:
    src: /Users/jackdescombes/projects/oura_proj/requirements.txt
    dest: "/srv/jenkins/requirements.txt"
    mode: "0755"
  tags: jenkins

- name: Ensure venv package is installed
  apt:
    name: python3-venv
    state: present
  tags: jenkins

# - name: Install specified python requirements in indicated (virtualenv)
#   pip:
#     requirements: /srv/jenkins/requirements.txt
#     virtualenv: /venvs/jenkins
#     virtualenv_python: python3

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  tags: jenkins

- name: Ensure ansible package is installed
  apt:
    name: ansible
    state: present
  tags: jenkins

- name: Manually create the initial virtualenv
  command:
    cmd: python3 -m venv /venvs/jenkins
    creates: /venvs/jenkins
  tags: jenkins

- name: Install specified python requirements in indicated (virtualenv)
  pip:
    requirements: /srv/jenkins/requirements.txt
    virtualenv: /venvs/jenkins
    virtualenv_python: python3
  tags: jenkins
